EnhancedCWE/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from user_profile.views import ProfileView

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url(r'^', include('frontpage.urls', namespace='frontpage')),
    url(r'^profile/$', ProfileView.as_view(), name='user_profile'),
    url(r'^robots\.txt/$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^accounts/', include('register.urls')),
    url(r'^app/login/', 'register.views.login'),
    url(r'^app/logout/', 'register.views.logout'),
    url(r'^app/password_change/', 'register.views.password_change'),
    url(r'^app/', include(admin.site.urls)),
    url(r'^autocomplete/', include('autocomplete_light.urls')),
    url(r'api/v1/', include('rest_api.urls')),   # Add "v1" to indicate the version.
    url(r'^comments/', include('comments.urls')),
]

comments/urls.py
from fluent_comments import urls as fluent_urls
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^delete/(\d+)/$', views.delete, name='comments-delete'),
] + fluent_urls.urlpatterns

frontpage/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^get_cwes/$', views.get_cwes, name='get_cwes'),
    url(r'^get_misusecases/$', views.get_misusecases, name='get_misusecases'),
    url(r'^get_usecases/$', views.get_usecases, name='get_usecases'),
    url(r'^create_issue_report/$', views.create_issue_report, name='create_issue_report'),
    url(r'^process_issue_report/$', views.process_issue_report, name='process_issue_report'),
]

register/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r"^login/$", views.login, name="account_login"),
    url(r'^', include('allauth.urls')),
]

rest_api/urls.py
from django.conf.urls import url
from rest_api import views

urlpatterns = [
    url(r'^cwe/text_related$', views.CWERelatedList.as_view(), name="restapi_CWETextRelated"),
    url(r'^cwe/all$', views.CWEAllList.as_view(), name="restapi_CWEAll"),
    url(r'^cwe/search_str', views.CWESearchSingleString.as_view(), name="restapi_CWESearchSingleString"),
    url(r'^misuse_case/cwe_related$', views.MisuseCaseRelated.as_view(), name="restapi_MisuseCase_CWERelated"),
    url(r'^use_case/misuse_case_related$', views.UseCaseRelated.as_view(), name="restapi_UseCase_MisuseCaseRelated"),
    url(r'^custom_muo/save$', views.SaveCustomMUO.as_view(), name="restapi_CustomMUO_Create"),
]

muo/models.py
from django.contrib.contenttypes.models import ContentType
from django.core import urlresolvers
from django.db import models, transaction
from django.conf import settings
from cwe.models import CWE
from base.models import BaseModel
from django.core.exceptions import ValidationError
from django.db.models.signals import post_delete, pre_delete, pre_save, post_save
from django.dispatch import receiver
from signals import *
from django.utils import timezone
from django.db.models import Q
from django.contrib.auth.models import  User

STATUS = [('draft', 'Draft'),
          ('in_review', 'In Review'),
          ('approved', 'Approved'),
          ('rejected', 'Rejected')]

ISSUE_TYPES = [('incorrect', 'Incorrect Content'),
                ('spam', 'Spam'),
                ('duplicate', 'Duplicate')]

ISSUE_STATUS = [('open', 'Open'),
                 ('investigating', 'Investigating'),
                ('reopened','Re-opened'),
                 ('resolved', 'Resolved')]

MISUSE_CASE_TYPE_CHOICES = [('existing', 'Existing'), ('new', 'New')]

OSR_PATTERN_CHOICES = [('ubiquitous', 'Ubiquitous'),
                       ('event-driven', 'Event-Driven'),
                       ('unwanted behavior', 'Unwanted Behavior'),
                       ('state-driven', 'State-Driven')]


# Tags are not used for now
class Tag(BaseModel):
    name = models.CharField(max_length=32, unique=True)

    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"
        default_permissions = ('add', 'change', 'delete', 'view')

    def __unicode__(self):
        return self.name


class MUOQuerySet(models.QuerySet):
    """
    Define custom methods for the MUO QuerySet
    """


    def approved(self):
        # Returns the queryset for all the approved MUO Containers
        if self.model == MUOContainer:
            return self.filter(status='approved', is_published=True)
        elif self.model == MisuseCase:
            return self.filter(muocontainer__status='approved', muocontainer__is_published=True)
        elif self.model == UseCase:
            return self.filter(muo_container__status='approved', muo_container__is_published=True)


    def rejected(self):
        # Returns the queryset for all the rejected MUO Containers
        if self.model == MUOContainer:
            return self.filter(status='rejected')
        elif self.model == MisuseCase:
            return self.filter(muocontainer__status='rejected')
        elif self.model == UseCase:
            return self.filter(muo_container__status='rejected')

    def draft(self):
        # Returns the queryset for all the draft MUO Containers
        if self.model == MUOContainer:
            return self.filter(status='draft')
        elif self.model == MisuseCase:
            return self.filter(muocontainer__status='draft')
        elif self.model == UseCase:
            return self.filter(muo_container__status='draft')

    def in_review(self):
        # Returns the queryset for all the in review MUO Containers
        if self.model == MUOContainer:
            return self.filter(status='in_review')
        elif self.model == MisuseCase:
            return self.filter(muocontainer__status='in_review')
        elif self.model == UseCase:
            return self.filter(muo_container__status='in_review')

    def custom(self):
        # Returns the queryset for all the custom MUO Containers
        if self.model == MUOContainer:
            return self.filter(is_custom=True)
        elif self.model == MisuseCase:
            return self.filter(muocontainer__is_custom=True)
        elif self.model == UseCase:
            return self.filter(muo_container__is_custom=True)

    def published(self):
        # Returns the queryset for all the published MUO Containers
        if self.model == MUOContainer:
            return self.filter(is_published=True)
        elif self.model == MisuseCase:
            return self.filter(muocontainer__is_published=True)
        elif self.model == UseCase:
            return self.filter(muo_container__is_published=True)

    def unpublished(self):
        # Returns the queryset for all the unpublished MUO Containers
        if self.model == MUOContainer:
            return self.filter(is_published=False)
        elif self.model == MisuseCase:
            return self.filter(muocontainer__is_published=False)
        elif self.model == UseCase:
            return self.filter(muo_container__is_published=False)

class MUOManager(models.Manager):
    """
    Define custom methods that can be called on the MUO Manager
    """

    def get_queryset(self):
        return MUOQuerySet(self.model, using=self._db)

    def approved(self):
        return self.get_queryset().approved()

    def draft(self):
        return self.get_queryset().draft()

    def rejected(self):
        return self.get_queryset().rejected()

    def in_review(self):
        return self.get_queryset().in_review()

    def custom(self):
        return self.get_queryset().custom()


class MisuseCase(BaseModel):
    cwes = models.ManyToManyField(CWE, related_name='misuse_cases')
    tags = models.ManyToManyField(Tag, blank=True)
    name = models.CharField(max_length=16, null=True, blank=True, db_index=True, default="/")
    misuse_case_description = models.TextField(null=True, blank=True, verbose_name="Brief Description")
    misuse_case_primary_actor = models.CharField(max_length=256, null=True, blank=True, verbose_name="Primary actor")
    misuse_case_secondary_actor = models.CharField(max_length=256, null=True, blank=True, verbose_name="Secondary actor")
    misuse_case_precondition = models.TextField(null=True, blank=True, verbose_name="Pre-condition")
    misuse_case_flow_of_events = models.TextField(null=True, blank=True, verbose_name="Flow of events")
    misuse_case_postcondition = models.TextField(null=True, blank=True, verbose_name="Post-condition")
    misuse_case_assumption = models.TextField(null=True, blank=True, verbose_name="Assumption")
    misuse_case_source = models.TextField(null=True, blank=True, verbose_name="Source")

    objects = MUOManager()  # Replace the default manager with the MUOManager

    class Meta:
        verbose_name = "Misuse Case"
        verbose_name_plural = "Misuse Cases"

    def __unicode__(self):
        return "%s - %s..." % (self.name, self.misuse_case_description[:70])


@receiver(post_save, sender=MisuseCase, dispatch_uid='misusecase_post_save_signal')
def post_save_misusecase(sender, instance, created, using, **kwargs):
    """ Set the value of the field 'name' after creating the object """
    if created:
        instance.name = "MU-{0:05d}".format(instance.id)
        instance.save()


class MUOContainer(BaseModel):
    name = models.CharField(max_length=16, null=True, blank=True, db_index=True, default="/")
    cwes = models.ManyToManyField(CWE, related_name='muo_container')

    misuse_case_type = models.CharField(max_length=16,
                                        null=True,
                                        blank=False,
                                        choices=MISUSE_CASE_TYPE_CHOICES,
                                        default='new',
                                        verbose_name='Misuse Case Type')

    misuse_case = models.ForeignKey(MisuseCase, on_delete=models.PROTECT, null=True, blank=True)

    misuse_case_name = models.CharField(max_length=16, null=True, blank=True, db_index=True, default="/")
    misuse_case_description = models.TextField(null=True, blank=True, verbose_name="Brief Description")
    misuse_case_primary_actor = models.CharField(max_length=256, null=True, blank=True, verbose_name="Primary actor")
    misuse_case_secondary_actor = models.CharField(max_length=256, null=True, blank=True, verbose_name="Secondary actor")
    misuse_case_precondition = models.TextField(null=True, blank=True, verbose_name="Pre-condition")
    misuse_case_flow_of_events = models.TextField(null=True, blank=True, verbose_name="Flow of events")
    misuse_case_postcondition = models.TextField(null=True, blank=True, verbose_name="Post-condition")
    misuse_case_assumption = models.TextField(null=True, blank=True, verbose_name="Assumption")
    misuse_case_source = models.TextField(null=True, blank=True, verbose_name="Source")

    reject_reason = models.TextField(null=True, blank=True)
    reviewed_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, null=True, blank=True)
    status = models.CharField(choices=STATUS, max_length=64, default='draft')
    is_custom = models.BooleanField(default=False, db_index=True)
    is_published = models.BooleanField(default=False, db_index=True)

    objects = MUOManager()  # Replace the default manager with the MUOManager

    class Meta:
        verbose_name = "MUO Container"
        verbose_name_plural = "MUO Containers"
        # additional permissions
        permissions = (
            ('can_approve', 'Can approve MUO container'),
            ('can_reject', 'Can reject MUO container'),
            ('can_edit_all', 'Can edit all MUO Containers'),
            ('can_view_all', 'Can view all MUO containers'),
        )

    @staticmethod
    def get_value_for_key_in_dict(dict, key):
        if key in dict:
            return dict[key]
        else:
            return ''

    @staticmethod
    def create_custom_muo(cwe_ids, misusecase, usecase, created_by):
        '''
        This is a static method that creates a custom MUO. It also established the relationship between the
        objects that has to be related on MUO creation i.e. relationship between cwes and misuse case, cwes
        and muo container, misuse case and muo container, misuse cae and use case.
        :param cwe_ids: (LIST of Integers) List of CWE IDs
        :param misusecase: (Dictionary) Dictionary contaning all the fields of the misuse case
        :param usecase: (Dictionary) Dictionary containing all the fields of the use case
        :param created_by: (USER)

frontpage/views.py
import autocomplete_light
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import Http404, JsonResponse, HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.template.response import TemplateResponse
from django.utils.safestring import mark_safe
from cwe.models import CWE
from muo.models import MisuseCase, UseCase, IssueReport
from .settings import SELECT_CWE_PAGE_LIMIT


# Home screen
def index(request):
    context = {'cwe_limit': SELECT_CWE_PAGE_LIMIT}
    return render(request, 'frontpage/index.html', context)



def get_cwes(request):
    """
    This view is called by muo search using ajax to get the list of CWEs for a given search query
    """
    if not request.is_ajax():
        return HttpResponseForbidden()

    query = request.GET.get('q')
    limit = SELECT_CWE_PAGE_LIMIT
    offset = (int(request.GET.get('page', 1)) - 1) * limit

    if query:
        if query.isdigit():
            cwes = CWE.objects.filter(Q(code__exact=query) | Q(name__icontains=query))
        else:
            cwes = CWE.objects.filter(name__icontains=query)
    else:
        cwes = CWE.objects.all()

    cwe_count = cwes.count()
    cwes = cwes[offset : offset + limit]
    results = [{'id': c.id,
                'text': 'CWE-%s: %s' % (c.code, c.name)} for c in cwes]
    return JsonResponse({'items': results, 'total_count': cwe_count})



def get_misusecases(request):
    """
    This view is called by muo search using ajax to display the misuse cases for given CWEs
    """
    if not request.is_ajax():
        raise HttpResponseForbidden()

    #  Get the selected CWE ids from the request
    selected_cwe_ids = request.POST.getlist('cwe_ids', None)
    search_term = request.POST.get('search_term', None)

    if len(selected_cwe_ids) == 0:
        # If list of CWE ids is empty return all the misuse cases
        misuse_cases = MisuseCase.objects.approved()
    else:
        #  Get the use cases for the selected CWE ids
        misuse_cases = MisuseCase.objects.filter(cwes__in=selected_cwe_ids).approved()

    if search_term:
        misuse_cases = misuse_cases.filter(Q(name__icontains=search_term) | Q(misuse_case_description__icontains=search_term))

    #  Create a context with all the corresponding misuse cases
    context = {'misuse_cases': misuse_cases,
               'search_term': search_term}

    return TemplateResponse(request, "frontpage/misusecase.html", context)


def get_usecases(request):
    """
    This view is called by muo search using ajax to display the use cases for a given misusecase
    """
    if not request.is_ajax():
        raise HttpResponseForbidden()

    misuse_case_id = request.POST['misuse_case_id']
    misuse_case = get_object_or_404(MisuseCase, pk=misuse_case_id)

    #  Create a context with all the corresponding use cases
    context = {'use_cases': misuse_case.usecase_set.approved()}

    return TemplateResponse(request, "frontpage/usecase.html", context)


def create_issue_report(request):
    """
    This view is called by muo search using ajax to display the report issue popup
    """
    if request.method == "POST":
        # read the usecase_id that triggered this action
        usecase_id = request.POST.get('usecase_id')
        usecase = get_object_or_404(UseCase, pk=usecase_id)

        # Render issue report form and default initial values, if any
        ModelForm = autocomplete_light.modelform_factory(IssueReport, fields=('usecase', 'usecase_duplicate', 'description', 'type'))
        form = ModelForm()

        context = dict(
            form=form,
            usecase=usecase,
        )
        return TemplateResponse(request, "frontpage/create_issue_report.html", context)
    else:
        raise Http404("Invalid access using GET request!")


def process_issue_report(request):
    """
    Handle adding new report created using muo search popup
    """
    if request.method == 'POST':

        ModelForm = autocomplete_light.modelform_factory(IssueReport, fields=('usecase', 'usecase_duplicate', 'description', 'type'))
        form = ModelForm(request.POST, request.FILES)
        if form.is_valid():
            new_object = form.save()
            messages.add_message(request, messages.SUCCESS,
                                 "Report %s has been created will be reviewed by our reviewers" % new_object.name)
        else:
            # submitted form is invalid
            errors = ["%s: %s" % (form.fields[field].label, error[0]) for field, error in form.errors.iteritems()]
            errors = '<br/>'.join(errors)
            messages.add_message(request, messages.ERROR, mark_safe("Invalid report content!<br/>%s" % errors) )

        return HttpResponseRedirect(reverse('frontpage:index'))

    else:
        raise Http404("Invalid access using GET request!")

frontpage/templates/frontpage/create_issue_report.html
{% load i18n widget_tweaks  %}

<div class="modal-dialog report-issue-container">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                    aria-hidden="true">×</span></button>
            <h4 class="modal-title">Report {{ usecase.name }}</h4>
        </div>
        <form class="form-horizontal" enctype="multipart/form-data" action="{% url 'frontpage:process_issue_report' %}" method="post" novalidate>
            <div class="modal-body">
                {% csrf_token %}
                <input id="id_usecase" name="usecase" value="{{ usecase.id }}" hidden="hidden"/>

                <div class="form-group ">
                    <div class="control-label col-md-3">
                        {{ form.type.label_tag }}
                    </div>
                    <div class="controls col-md-12">
                        {{ form.type|add_class:"form-control"  }}
                    </div>

                    <div id="duplicate-container" style="display: none">
                        <div class="control-label col-md-6">
                            {{ form.usecase_duplicate.label_tag }}
                        </div>
                        <div class="controls col-md-12">
                            {{ form.usecase_duplicate|add_class:"form-control"  }}
                        </div>
                    </div>

                    <div class="control-label col-md-6">
                        {{ form.description.label_tag }}
                    </div>
                    <div class="controls col-md-12">
                        {{ form.description|add_class:"form-control"|attr:"rows:3"|attr:"placeholder:Enter issue description..." }}
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                <input type="submit" id="report_button" class="btn btn-danger" value="{% trans 'Report' %}"
                       name="_report" disabled="disabled" />
            </div>
        </form>
    </div>
</div>

<script type="application/javascript">
    jQuery(function() {
        var container = $(".report-issue-container");
        var type = container.find('#id_type');
        var submit_button = container.find('#report_button');
        var duplicate_usecase = container.find('#id_usecase_duplicate');
        var duplicate_usecase_container = container.find('#duplicate-container');

        {# Handle disabling the submit button based on type choice and hiding/showing the duplicate use case selection #}
        type.on('change', function(e){
            if (type.val()) {
                submit_button.prop("disabled",false);
            } else {
                submit_button.prop("disabled",true);
            }

            if (type.val() == 'duplicate') {
                duplicate_usecase_container.show();
                if (duplicate_usecase.val() == null){
                    submit_button.prop("disabled",true);
                } else {
                    submit_button.prop("disabled",false);
                }

            } else {
                duplicate_usecase_container.hide();
            }
        });

        {# Handle disabiling the submit button based on value of usecase duplicate #}
        duplicate_usecase.on('change', function(e){

            if (duplicate_usecase.val() != null ) {
                if (type.val()) {
                    submit_button.prop("disabled",false);
                } else {
                    submit_button.prop("disabled",true);
                }
            } else {
                if (type.val() && type.val() != 'duplicate') {
                    submit_button.prop("disabled",false);
                } else {
                    submit_button.prop("disabled",true);
                }
            }
        });
    });

</script>

frontpage/templates/frontpage/index.html
{% extends "frontpage/base.html" %}
{% load i18n static crispy_forms_tags widget_tweaks %}

{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "dist/css/select2.min.css" %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'frontpage/frontpage.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'fluent_comments/css/ajaxcomments.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'comments/comments.css' %}" />
{% endblock %}

{% block extrahead %}
    {{ block.super }}
    <script src={% static "dist/js/select2.min.js" %}></script>
    <script src={% static "frontpage/frontpage.js" %}></script>
    <script type="text/javascript" src="{% static 'comments/comments.js' %}"></script>
{% endblock %}

{% block navbar %} {% endblock %}

{% block pre_container %}
    <div class="marquee" id="marquee" role="main" tabindex="-1">
        <div class="container">
            <span class="more-icon more-icon-lg more-icon-outline">
                MORE
            </span>

            <h2><b>M</b>alware-driven <b>O</b>verlooked <b>RE</b>quirements</h2>

            <p class="lead"> This site is meant to guide requirement engineers in identifying security requirements
                appropriate for their project. The site focuses on exploited vulnerabilities resulting from design
                flaws. For each new publicly posted exploited vulnerability, contributors can identify and provide a
                misuse case, use case and the overlooked security requirement(s) that created the vulnerability. This
                helps requirements engineers avoid these and potentially other vulnerabilities in their systems. Please
                register to use and enjoy.</p>

            {% if not user.is_authenticated %}
                <p class="lead">
                    <a href="{% url 'account_signup' %}" class="btn btn-outline-inverse btn-lg">Register Now</a>
                </p>
            {% endif %}

        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="col-md-12">

        <form class="form-horizontal" action method="post" novalidate>
            {% csrf_token %}

            <div class="col-md-12">
                <div id="div_id_cwes" class=" {% if form.cwes.errors %} has-error {% endif %}">
                    <label for="div_id_cwes" class="control-label  requiredField">
                        {{ form.cwes.label }}
                    </label>


                    <div class="input-group input-group-lg">

                        <select id="id_cwes" name="cwes" multiple="multiple" style="width:100%;height:46px"
                                data-ajax-url="{% url 'frontpage:get_cwes' %}"
                                data-page-limit="{{ cwe_limit }}"></select>

                        <div class="input-group-btn">
                            <button class="btn btn-success btn-flat" id="cwe-submit-button" type="button"
                                    data-ajax-url="{% url 'frontpage:get_misusecases' %}"
                                    title="Misuse Cases, Use Cases &<br/>Overlooked Security Requirements"
                                    data-html="true">Get MUOs
                            </button>
                        </div>
                        <!-- /btn-group -->
                    </div>


                    {% if form.cwes.errors %}
                        {% for error in form.cwes.errors %}
                            <p class="help-block"><strong>{{ error|escape }}</strong></p>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>

            <div class="col-md-12 muo-search-container" style="display: none;">
                <div class="box box-primary">
                    <div class="box-body">
                        <div>
                            <div id="misuse-case-title-label">Misuse Cases</div>
                            <div id="use-case-title-label">Use Cases & Overlooked Security Requirements</div>
                        </div>
                        <hr style="margin: 0px;"/>
                        <div class="slim-scroll-div"></div>
                        {# slim-scroll-div is to loaded from misusecase.html after the ajax response #}
                        <div class="fat-scroll-div"></div>
                        {# fat-scroll-div is to loaded from usecase.html after the ajax response #}
                    </div>
                </div>
            </div>

            {# Modal used for popups, such as report inappropriate#}
            <div class="modal fade" id="muo-modal" tabindex="-1" role="dialog" aria-labelledby="" aria-hidden="true"></div>


        </form>

{% endblock %}

frontpage/templates/frontpage/usecase.html
{% load comments static %}

<script type="text/javascript" src="{% static 'fluent_comments/js/ajaxcomments.js' %}"></script>

<div class="fat-scroll-div">
    {% for usecase in use_cases %}
        <div class="use-case-container">
            <div class="use-case-header">
                <label class="pull-left">Use Case: {{ usecase.name }}</label>
                <label id="muo-date-header">{{ usecase.created_at }}</label>
            </div>
            <div class="use-case-div">
                <div>
                    <label class="heading">Description</label>
                </div>
                <div class="text">{{ usecase.use_case_description|linebreaks }}</div>
            </div>

            {% if usecase.use_case_primary_actor %}
            <div class="use-case-div">
                <div>
                    <label class="heading">Primary Actor</label>
                </div>
                <div class="text">{{ usecase.use_case_primary_actor|linebreaks }}</div>
            </div>
            {% endif %}

            {% if usecase.use_case_secondary_actor %}
            <div class="use-case-div">
                <div>
                    <label class="heading">Secondary Actor</label>
                </div>
                <div class="text">{{ usecase.use_case_secondary_actor|linebreaks }}</div>
            </div>
            {% endif %}

            {% if usecase.use_case_precondition %}
            <div class="use-case-div">
                <div>
                    <label class="heading">Pre-condition</label>
                </div>
                <div class="text">{{ usecase.use_case_precondition|linebreaks }}</div>
            </div>
            {% endif %}

            {% if usecase.use_case_flow_of_events %}
            <div class="use-case-div">
                <div>
                    <label class="heading">Flow of Events</label>
                </div>
                <div class="text">{{ usecase.use_case_flow_of_events|linebreaks }}</div>
            </div>
            {% endif %}

            {% if usecase.use_case_postcondition %}
            <div class="use-case-div">
                <div>
                    <label class="heading">Post-condition</label>
                </div>
                <div class="text">{{ usecase.use_case_postcondition|linebreaks }}</div>
            </div>
            {% endif %}

            {% if usecase.use_case_assumption %}
            <div class="use-case-div">
                <div>
                    <label class="heading">Assumption</label>
                </div>
                <div class="text">{{ usecase.use_case_assumption|linebreaks }}</div>
            </div>
            {% endif %}

            {% if usecase.use_case_source %}
            <div class="use-case-div">
                <div>
                    <label class="heading">Source</label>
                </div>
                <div class="text">{{ usecase.use_case_source|linebreaks }}</div>
            </div>
            {% endif %}

            <div class="use-case-div">
                <div>
                    <label class="osr-heading">Overlooked Security Requirement:</label>
                </div>
                <div class="text">{{ usecase.osr|linebreaks }}</div>
            </div>

            <div class="usecase-footer">
                <div class="pull-left">
{#                    <a href="" class="btn btn-xs">#}
{#                        <span class="fa fa-thumbs-o-up"></span>#}
{#                    </a>#}
{#                    <a href="" class="btn btn-xs">#}
{#                        <span class="fa fa-thumbs-o-down"></span>#}
{#                    </a>#}
                    {% if user.is_authenticated %}
                        <a href="#comments-block-{{ usecase.id }}" class="btn btn-xs">
                        <span class="fa fa-comment-o ">
                        </span>
                        {% get_comment_count for usecase as comment_count %} {{ comment_count }} comments
                        </a>
                    {% endif %}

                </div>

                <div class="pull-right">
                    {% if user.is_authenticated %}
                    <a href="#muo-modal" class="btn btn-xs" data-toggle="modal"
                       data-ajax-url="{% url 'frontpage:create_issue_report' %}"
                       data-usecase-id="{{ usecase.pk }}"
                       title data-original-title="Report Issue">
                        <span class="fa fa-exclamation-triangle"></span>
                        Report Issue
                    </a>
                    {% endif %}
                </div>
            </div>

            {% if user.is_authenticated %}
            <div class="comments-container" id="comments-block-{{ usecase.id }}">
                {% render_comment_list for usecase %}
                {% render_comment_form for usecase %}
            </div>
            {% endif %}

        </div>
    {% endfor %}


</div>